name: Simple CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run code format check with flake8
        run: |
          pip install flake8
          flake8 .

      - name: Run Semgrep for security analysis
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/python"

      - name: Run Gitleaks to scan for sensitive data
        uses: zricethezav/gitleaks-action@v1
        with:
          scan: true

      - name: Install Safety and check dependencies
        run: |
          pip install safety
          safety check --full-report
